# Generated by Django 5.0.6 on 2024-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_complaints_address_remove_complaints_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='house_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
