# Generated by Django 5.0.6 on 2024-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
