# Generated by Django 5.0.6 on 2024-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_messages_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='messages',
            name='reply_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
