# Generated by Django 5.0.6 on 2024-06-05 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_text_messages_question_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(null=True)),
                ('personal_account', models.CharField(max_length=12, null=True)),
                ('hot_watter_supply', models.IntegerField(null=True)),
                ('cold_watter_supply', models.IntegerField(null=True)),
                ('gas_supply', models.IntegerField(null=True)),
                ('electricity_supply', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meter_reading',
                'verbose_name_plural': 'meter_readings',
                'db_table': 'meter_readings',
            },
        ),
    ]
