# Generated by Django 5.0.6 on 2024-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_meterreadings'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reply_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meterreadings',
            name='personal_account',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
