# Generated by Django 5.0.6 on 2024-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_messages_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='reply_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='send_date',
            field=models.DateTimeField(null=True),
        ),
    ]
