# Generated by Django 5.0.6 on 2024-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_messages_reply_date_alter_messages_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='personal_account',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
